[[constraint]]
  name = "github.com/docker/distribution"
  source = "https://github.com/docker/distribution.git"
  version = "v2.7.0"

[[constraint]]
  name = "github.com/Lambda-NIC/faas"
  branch = "master"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.0"

[[override]]
  name = "github.com/nats-io/go-nats"
  version = "v1.5.0"

[[constraint]]
  name = "github.com/Lambda-NIC/nats-queue-worker"
  branch = "master"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "0.8.0"

[[constraint]]
  name = "github.com/Lambda-NIC/faas-provider"
  branch = "master"
